language: node_js

sudo: false

node_js:
  - "6"

install:
  - npm install
  - npm install -g jasmine gulp typescript

env:
  - MONGODB=mongodb://localhost

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.6.11.tgz
  - tar -zxvf mongodb-linux-x86_64-2.6.11.tgz
  - mkdir -p ./data/db
  - ./mongodb-linux-x86_64-2.6.11/bin/mongod --fork --nopreallocj --dbpath ./data/db --syslog --port 27017
  
script:
  - gulp coverage

after_script:
  - npm i coveralls && cat ./coverage/lcov-remap.info | coveralls
